### ISSUE TITLE
[Question] Running cypress test with elasticsearch

### ISSUE THREAD

**Issue by kortirso** [shakacode/cypress-on-rails#71]
Our Rails app uses elasticsearch and we are integrating cypress for integration tests
gem 'elasticsearch-model'
gem 'cypress-on-rails'

is there any best-practice examples how can we run test cluster of elasticsearch Elasticsearch::Extensions::Test::Cluster.start before all cypress tests and stop it after all tests?

right now I added Elasticsearch::Extensions::Test::Cluster.start to cypress helper and looks like first test spends 40 seconds to run it, but for others - no waiting time

**Comment by grantspeelman** [comment]
@kortirso no examples of this that i am aware of.
Can i ask though why must the rails server start elasticsearch? 

We usually start all services (like postgresql and redis) before we start the rails server. I would most likely do the same with elasticsearch.

**Comment by yagudaev** [comment]
Same here we use elastic search through searchkick. We actually have a `Procfile.test` that we run like `heroku local -f Procfile.test` which includes running any other services locally.

Locally I would just run elasticsearch through `brew services`. On CI, there is a docker image for ES you can use, I've had some issues with memory usage on JVM on CircleCI sometimes. We've switched to Buildkite now at work.

To clean ES we just have a `search/reindex` task before each test run. One thing I wish I knew back then is to have no data. We have a sort of seeds file for our tests called `basicScenario`, but I recommend just using factories and setting up each page with its own data. Otherwise it is slow.

Also you can create all the indexes at start up time of the rails server.

Maybe you can help contribute a wiki doc to ES setup wit the `elasticsearch-rails` gem. I'd be happy to contribute to it too.

**Comment by kortirso** [comment]
thanks,
so in general we run everything with Procfile
rails s -e test
elasticsearch

with env file that tells use development port of elasticsearch for test rails environment
and indexing models in cypress seeds
